### ISSUE TITLE
BCrypt密码校验方法写错了

### ISSUE THREAD

**Issue by ChangYunQing** [waylau/new-star-blog#3]
UserspaceController.saveProfile  327行

> // 判断密码是否做了变更
		String rawPassword = originalUser.getPassword();
		PasswordEncoder encoder = new BCryptPasswordEncoder();
		String encodePasswd = encoder.encode(user.getPassword());
		boolean isMatch = encoder.matches(rawPassword, encodePasswd);
>
应该是
boolean isMatch = encoder.matches(user.getPassword(), originalUser.getPassword());
第一个参数是表单传过来的密码（不用加密），第二个参数是数据库密码

**Comment by waylau** [comment]
@ChangYunQing 

第一个参数是表单传过来的密码可能有两种场景：
1. 如果是没有修改过的密码，就是从数据库直接查出来的返回给前台表单的密码（密文，已经是加密过的了）
2. 如果是修改后的密码（新密码），就是没有加过密的密码（明文）。
