### ISSUE TITLE
首页热门标签，中文标签会出现每个字都分开

### ISSUE THREAD

**Issue by jontyhua** [waylau/new-star-blog#5]
在首页的热门标签中，如果这个标签内容是中文的，会出现中文分开。是listTop30Tags()的actiontypeBucket.getKey()有问题吗？
请问怎么解决这个中文问题呢

**Comment by waylau** [comment]
@jontyhua  是ES的问题，可以安装中文分词来解决   https://waylau.com/elasticsearch-use-ik-analysis/

**Comment by jontyhua** [comment]
好的，非常感谢您！
如果es中的data文件夹丢失，那么是不是首页的数据就恢复不了了呢

Way Lau <notifications@github.com> 于 2019年4月28日周日 下午3:14写道：

**Comment by waylau** [comment]
@jontyhua  是的，你看程序就知道
