### ISSUE TITLE
当个人用户修改头像后，elasticsearch中的头像地址更新不了，

### ISSUE THREAD

**Issue by yylljun** [waylau/new-star-blog#6]
我写了上传新头像删除旧头像，然后index列表修改后就不能显示最新头像了，elasticsearch没更新，不知道有没有批量更新的方法.

**Comment by waylau** [comment]
@yylljun  头像跟 ES没有关系吧？

**Comment by yylljun** [comment]
EsBlog 中有avater 然后index页面用的List<EsBlog> 遍历 用的也是里面的图片view链接,我上传一个头像会删除原来的头像，然后EsBlog里面的avater就找部到图片了，就是不知道咋个写 根据username批量修改EsBlog的avater
@waylau

**Comment by waylau** [comment]
ES 和 MySQL 的数据源是同步的啊，修改的内容，同时改到到ES 和MySQL 。课程里面有讲如何实现哦~
