### ISSUE TITLE
图片可以写入到数据库，但每次重启文件服务器和elesticsearch和项目 ，发现：头像和博文中的图片数据都无法显示到页面，但是查看数据库里是有数据的。

### ISSUE THREAD

**Issue by firewolfgirl** [waylau/new-star-blog#7]
图片可以写入到数据库，但每次重启文件服务器和elesticsearch和项目 ，发现：头像和博文中的图片数据都无法显示到页面，但是查看数据库里是有数据的。

**Comment by waylau** [comment]
文件服务器(Mogodb)和elesticsearch默认都是内存模式，所以重启后数据丢失。可以改为独立部署模式。
