### ISSUE TITLE
Markdown插件的解析不彻底的问题

### ISSUE THREAD

**Issue by Hyman1993** [waylau/new-star-blog#8]
请问一下卫哥，写博客的时候，采用Markdown的语法排版，在预览的时候，能正确显示出来，但是一发表后，在博客页面有些Markdown的语法无法正确解析，请问这是什么原因？

**Comment by waylau** [comment]
@Hyman1993   这个属于正常情况。
前台和后台用的是不同的Markdown插件，所以对于Markdown语法支持程度不同。

建议使用的使用，用普遍的语法。

**Comment by Hyman1993** [comment]
好的，谢谢卫哥
