### ISSUE TITLE
es正常启动started之后报错

### ISSUE THREAD

**Issue by firewolfgirl** [waylau/new-star-blog#9]
es正常启动started之后报错：
[DEBUG][action.admin.indices.mapping.put] [Alicia Masters] failed to put mappings on indices [[blog]], type [blog]
MapperParsingException[No type specified for field [blogId]]

**Comment by waylau** [comment]
版本问题吧。~看下版本，是否与 https://github.com/waylau/new-star-blog  一致？

**Comment by firewolfgirl** [comment]
![image](https://user-images.githubusercontent.com/40993340/58478584-02dc3780-8189-11e9-819e-90d754a5ef1a.png)
不一致　我重新下载ｅｓ试试

**Comment by firewolfgirl** [comment]
重新下载es解压后启动发现报错了

**Comment by firewolfgirl** [comment]
![image](https://user-images.githubusercontent.com/40993340/58542499-4b9afb80-8230-11e9-8bea-88ccaf3a4e81.png)

es的版本改成5.5.0那么Jna的版本要改吗

**Comment by waylau** [comment]
@firewolfgirl  你这个是慕课网课程里面的问题吧？你去课程讨论区提问。
那个和这个不是一个项目。
